# require( 'sinatra' )
# require( 'sinatra/contrib/all' )
require_relative( '../models/booking.rb' )
require_relative( '../models/class.rb' )
require_relative( '../models/member.rb' )
also_reload( '../models/*' )
